apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-oauth-provider
  namespace: default
spec:
  provider: vault
  parameters:
    roleName: "vault-role"
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    objects: |
      - objectName: "GITHUB_CLIENT_ID"
        secretPath: "secret/bram_vortex_oauth"
        secretKey: "GITHUB_CLIENT_ID"
      - objectName: "GITHUB_CLIENT_SECRET"
        secretPath: "secret/bram_vortex_oauth"
        secretKey: "GITHUB_CLIENT_SECRET"
  secretObjects:
    - secretName: oauth-k8s-secret
      type: Opaque
      data:
        - objectName: "GITHUB_CLIENT_ID"
          key: "client-id"
        - objectName: "GITHUB_CLIENT_SECRET"
          key: "client-secret"